wandb_version: 1

exp_name:
  desc: null
  value: main
alg_name:
  desc: null
  value: PPO
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ec523
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: true
save_model:
  desc: null
  value: false
upload_model:
  desc: null
  value: false
env_id:
  desc: null
  value: Pendulum-v1
total_timesteps:
  desc: null
  value: 1000000
learning_rate:
  desc: null
  value: 0.0003
num_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 10000
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 1.0
target_network_frequency:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 0
start_e:
  desc: null
  value: 1
end_e:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.5
learning_starts:
  desc: null
  value: 10000
train_frequency:
  desc: null
  value: 10
num_steps:
  desc: null
  value: 2048
anneal_lr:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 32
update_epochs:
  desc: null
  value: 10
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
minibatch_size:
  desc: null
  value: 0
num_iterations:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.9.7
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713969858.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.7
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
